### ISSUE TITLE
Add version

### ISSUE THREAD

**Issue by luizbills** [kittykatattack/ga#43]
jus a constant `GA.VERSION`

**Comment by kittykatattack** [comment]
Thanks, do you have a suggestion on how to implement this?

**Comment by luizbills** [comment]
Just add a line in the source  `GA.VERSION = '0.0.1'` and bump it on every update. I recommend to use [Semantic Versioning](http://semver.org/). An branch `dev` is useful too, for better release control.

**Comment by kittykatattack** [comment]
`dev` branch added... considering the best the way to do versioning and will get back to you 😄

**Comment by luizbills** [comment]
A "changelog" and a "roadmap" will be great too.
