### ISSUE TITLE
Alien Armada not working

### ISSUE THREAD

**Issue by fzzylogic** [kittykatattack/ga#48]
Hi, 

I'm working through the tutorial and loving GA! The tutorial is very good, just what one needs when one is new to this. Just wanted to mention that the alienArmada demo is not working on Chrome / Firefox on Windows 10. I tried rolling back in git to when the game was first submitted, but the problem was there too. I also tried testing via the raw git link (to rule out the problem being with civetweb, the little webserver i'm using), however the problem remained.

Error returned is:
plugins.js:408 Uncaught ReferenceError: sprite is not defined
ga.move @   plugins.js:408
play    @   04_alienArmada.html:267
update  @   ga.js:343
gameLoop    @   ga.js:278

Thanks!

**Comment by qsrahman** [comment]
Gee! there is a bug, rather a typo in plugins.js move method :

```
ga.move = function(sprites) {
    if (sprites instanceof Array === false) {
      internal_move(sprites)
    } else {
      for (var i = 0; i < sprites.length; i++) {
        internal_move(sprite[i])     //<-----------(1)
      }
    }
  };
```

change the line (1) to:
```
internal_move(sprites[i])
```
:)

**Comment by fzzylogic** [comment]
Cool thanks! I should have used the unminified version of plugins.js and just looked at the code..
