### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by bsorrentino** [kittykatattack/ga#69]
Hi

This is mostly a question. I would like to know if you are interested to add support for [typescript](https://www.typescriptlang.org/) language.

I've forked your project and, without change anything of your runtime js code, I have added typescript definitions in order to have for free **type checking**, **intellisense**, **inline help** etc .. Moreover I've converted tutorial and examples  ([see fork](https://github.com/bsorrentino/ga/tree/develop)) ([see typedoc generate doc](https://bsorrentino.github.io/ga/))

If yes, I'll provide you the PR

**Comment by kittykatattack** [comment]
Wow, that's amazing!!!
I wouldn't like to use Typescript in this main repo (it's all about minimalism), but we should definitely link to your fork in the docs.

(...Oh, and if anyone out there reading this would like to build an Elm (http://elm-lang.org) wrapper, please let me know!)

**Comment by Permagate** [comment]
Thanks for the definition files @bsorrentino. Rather than adding it in the main repo, might I suggest to publish it in a separate package `@types/Ga!` ?

**Comment by bsorrentino** [comment]
Ok

I’ll push to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/README.md) for publishing as @types

**Comment by bsorrentino** [comment]
Hi @kittykatattack referring to @Permagate request could I publish on npm ( `ga-ts` ) this package using the typescript definitions from my fork ?

**Note**
> Keep in mind that I not have changed your javascript implementation

**Comment by kittykatattack** [comment]
@bsorrentino Yes, of course, go ahead!
Thanks for doing all that, it's amazing!

We should add a link to your fork on the README too.

-kk.

**Comment by bsorrentino** [comment]
Thank you @kittykatattack for your amazing work ...

**Comment by bsorrentino** [comment]
I've published project on [npm|https://www.npmjs.com/package/kka-ga].

@Permagate typescript definitions are embedded so, if you use `npm` to download project (`npm i kka-ga` ) it already works for typescript

**Comment by Permagate** [comment]
Need to add `/// <reference types="kka-ga" />` somewhere in the project in addition to installing `kka-ga`. It works well otherwise, thanks @bsorrentino!

**Comment by bsorrentino** [comment]
@Permagate,  that should be one way to use it.

Really I would wanted that definition was auto loaded for this reason I've followed the standard naming `index.d.ts`. But it seems not enough .. I'll try to figure out how to do it
